export const DATA_DEFINITION = [
    {
        "id": 1,
        "name": "Derrek",
        "lastName": "Vokins",
        "phone": "5176751347",
        "email": "dvokins0@businessinsider.com",
        "anualRevenue": 90492,
        "registrationDate": "01/10/2024",
        "state": "Michigan",
        "status": "Available",
        "hasNotification": true,
      }, {
        "id": 2,
        "name": "Paddy",
        "lastName": "Gatherer",
        "phone": "4101207070",
        "email": "pgatherer1@microsoft.com",
        "anualRevenue": 73677,
        "registrationDate": "04/29/2023",
        "state": "Maryland",
        "status": "Not Available"
      }, {
        "id": 3,
        "name": "Tucker",
        "lastName": "Abden",
        "phone": "4173388729",
        "email": "tabden2@wikipedia.org",
        "anualRevenue": 83431,
        "registrationDate": "04/27/2023",
        "state": "Missouri",
        "status": "Not Available"
      }, {
        "id": 4,
        "name": "Margalo",
        "lastName": "Hawley",
        "phone": "5412114304",
        "email": "mhawley3@msu.edu",
        "anualRevenue": 38980,
        "registrationDate": "07/24/2023",
        "state": "Oregon",
        "status": "Not Available"
      }, {
        "id": 5,
        "name": "Bea",
        "lastName": "MacGray",
        "phone": "4144374170",
        "email": "bmacgray4@slashdot.org",
        "anualRevenue": 21770,
        "registrationDate": "01/04/2024",
        "state": "Wisconsin",
        "status": "Available"
      }, {
        "id": 6,
        "name": "Benedicta",
        "lastName": "Radborn",
        "phone": "7169145256",
        "email": "bradborn5@theglobeandmail.com",
        "anualRevenue": 60940,
        "registrationDate": "04/19/2023",
        "state": "New York",
        "status": "Available"
      }, {
        "id": 7,
        "name": "Zak",
        "lastName": "Congreve",
        "phone": "2024104884",
        "email": "zcongreve6@ehow.com",
        "anualRevenue": 55588,
        "registrationDate": "11/01/2023",
        "state": "District of Columbia",
        "status": "Available"
      }, {
        "id": 8,
        "name": "Dorian",
        "lastName": "Sellack",
        "phone": "9713046120",
        "email": "dsellack7@mysql.com",
        "anualRevenue": 53249,
        "registrationDate": "02/25/2023",
        "state": "Oregon",
        "status": "Not Available"
      }, {
        "id": 9,
        "name": "Cindi",
        "lastName": "Ogus",
        "phone": "5619228467",
        "email": "cogus8@twitter.com",
        "anualRevenue": 31617,
        "registrationDate": "09/28/2023",
        "state": "Florida",
        "status": "Available"
      }, {
        "id": 10,
        "name": "Viviyan",
        "lastName": "Signore",
        "phone": "4056842888",
        "email": "vsignore9@jigsy.com",
        "anualRevenue": 16364,
        "registrationDate": "10/09/2023",
        "state": "Oklahoma",
        "status": "Available"
      }, {
        "id": 11,
        "name": "Gordy",
        "lastName": "Houdhury",
        "phone": "2088137260",
        "email": "ghoudhurya@harvard.edu",
        "anualRevenue": 58140,
        "registrationDate": "12/23/2023",
        "state": "Idaho",
        "status": "Available"
      }, {
        "id": 12,
        "name": "Darcie",
        "lastName": "Wabersich",
        "phone": "8595575825",
        "email": "dwabersichb@cisco.com",
        "anualRevenue": 15148,
        "registrationDate": "08/31/2023",
        "state": "Kentucky",
        "status": "Available"
      }, {
        "id": 13,
        "name": "Fernanda",
        "lastName": "Scholer",
        "phone": "3187341410",
        "email": "fscholerc@hugedomains.com",
        "anualRevenue": 81316,
        "registrationDate": "02/06/2023",
        "state": "Louisiana",
        "status": "Available"
      }, {
        "id": 14,
        "name": "Caresa",
        "lastName": "Bulch",
        "phone": "5047281342",
        "email": "cbulchd@bigcartel.com",
        "anualRevenue": 58816,
        "registrationDate": "07/28/2023",
        "state": "Louisiana",
        "status": "Not Available"
      }, {
        "id": 15,
        "name": "Teresina",
        "lastName": "Birt",
        "phone": "7544837081",
        "email": "tbirte@msu.edu",
        "anualRevenue": 51881,
        "registrationDate": "01/17/2024",
        "state": "Florida",
        "status": "Not Available"
      }, {
        "id": 16,
        "name": "Raimundo",
        "lastName": "Jimes",
        "phone": "2147958183",
        "email": "rjimesf@people.com.cn",
        "anualRevenue": 81115,
        "registrationDate": "10/10/2023",
        "state": "Texas",
        "status": "Available"
      }, {
        "id": 17,
        "name": "Lula",
        "lastName": "Pallatina",
        "phone": "9153785633",
        "email": "lpallatinag@nationalgeographic.com",
        "anualRevenue": 58771,
        "registrationDate": "11/20/2023",
        "state": "Texas",
        "status": "Not Available"
      }, {
        "id": 18,
        "name": "Melloney",
        "lastName": "Smitheram",
        "phone": "9017523785",
        "email": "msmitheramh@cafepress.com",
        "anualRevenue": 32332,
        "registrationDate": "05/22/2023",
        "state": "Tennessee",
        "status": "Not Available"
      }, {
        "id": 19,
        "name": "Lynsey",
        "lastName": "Buzek",
        "phone": "4028423051",
        "email": "lbuzeki@deliciousdays.com",
        "anualRevenue": 39503,
        "registrationDate": "05/12/2023",
        "state": "Nebraska",
        "status": "Available"
      }, {
        "id": 20,
        "name": "Fina",
        "lastName": "Hassur",
        "phone": "6025766795",
        "email": "fhassurj@prweb.com",
        "anualRevenue": 49336,
        "registrationDate": "10/11/2023",
        "state": "Arizona",
        "status": "Available"
      }, {
        "id": 21,
        "name": "Silva",
        "lastName": "Reynoldson",
        "phone": "2054886711",
        "email": "sreynoldsonk@ustream.tv",
        "anualRevenue": 25141,
        "registrationDate": "11/14/2023",
        "state": "Alabama",
        "status": "Not Available"
      }, {
        "id": 22,
        "name": "Roi",
        "lastName": "Addenbrooke",
        "phone": "5051921863",
        "email": "raddenbrookel@yahoo.co.jp",
        "anualRevenue": 26629,
        "registrationDate": "02/09/2023",
        "state": "New Mexico",
        "status": "Available"
      }, {
        "id": 23,
        "name": "Adele",
        "lastName": "Khristyukhin",
        "phone": "6143759186",
        "email": "akhristyukhinm@fema.gov",
        "anualRevenue": 38724,
        "registrationDate": "10/04/2023",
        "state": "Ohio",
        "status": "Available"
      }, {
        "id": 24,
        "name": "Carina",
        "lastName": "Rumble",
        "phone": "9799694301",
        "email": "crumblen@github.com",
        "anualRevenue": 95850,
        "registrationDate": "04/02/2023",
        "state": "Texas",
        "status": "Available"
      }, {
        "id": 25,
        "name": "Pennie",
        "lastName": "Lamacraft",
        "phone": "5717658597",
        "email": "plamacrafto@merriam-webster.com",
        "anualRevenue": 84655,
        "registrationDate": "01/29/2024",
        "state": "Virginia",
        "status": "Available"
      }, {
        "id": 26,
        "name": "Janessa",
        "lastName": "Euler",
        "phone": "3059011271",
        "email": "jeulerp@sun.com",
        "anualRevenue": 31463,
        "registrationDate": "04/05/2023",
        "state": "Florida",
        "status": "Not Available"
      }, {
        "id": 27,
        "name": "Mohandas",
        "lastName": "Mintoff",
        "phone": "4149361926",
        "email": "mmintoffq@google.ru",
        "anualRevenue": 14131,
        "registrationDate": "02/28/2023",
        "state": "Wisconsin",
        "status": "Available"
      }, {
        "id": 28,
        "name": "Puff",
        "lastName": "Pointon",
        "phone": "2105530204",
        "email": "ppointonr@ebay.co.uk",
        "anualRevenue": 60504,
        "registrationDate": "11/04/2023",
        "state": "Texas",
        "status": "Available"
      }, {
        "id": 29,
        "name": "Fan",
        "lastName": "Meltetal",
        "phone": "9173553279",
        "email": "fmeltetals@goodreads.com",
        "anualRevenue": 69652,
        "registrationDate": "07/16/2023",
        "state": "New York",
        "status": "Available"
      }, {
        "id": 30,
        "name": "Alidia",
        "lastName": "Dobey",
        "phone": "2155731382",
        "email": "adobeyt@odnoklassniki.ru",
        "anualRevenue": 20209,
        "registrationDate": "11/11/2023",
        "state": "Pennsylvania",
        "status": "Not Available"
      }, {
        "id": 31,
        "name": "Darn",
        "lastName": "Dimitresco",
        "phone": "9072413798",
        "email": "ddimitrescou@wikimedia.org",
        "anualRevenue": 43276,
        "registrationDate": "01/30/2024",
        "state": "Alaska",
        "status": "Available"
      }, {
        "id": 32,
        "name": "Tanya",
        "lastName": "Baseggio",
        "phone": "5595921521",
        "email": "tbaseggiov@sun.com",
        "anualRevenue": 30065,
        "registrationDate": "08/09/2023",
        "state": "California",
        "status": "Available"
      }, {
        "id": 33,
        "name": "Giacobo",
        "lastName": "Wooller",
        "phone": "3041968716",
        "email": "gwoollerw@google.co.uk",
        "anualRevenue": 34701,
        "registrationDate": "01/14/2024",
        "state": "West Virginia",
        "status": "Available"
      }, {
        "id": 34,
        "name": "Ray",
        "lastName": "Mahody",
        "phone": "4235005585",
        "email": "rmahodyx@rakuten.co.jp",
        "anualRevenue": 58813,
        "registrationDate": "08/26/2023",
        "state": "Tennessee",
        "status": "Not Available"
      }, {
        "id": 35,
        "name": "Edythe",
        "lastName": "Longhorn",
        "phone": "6502491850",
        "email": "elonghorny@mysql.com",
        "anualRevenue": 15758,
        "registrationDate": "01/06/2024",
        "state": "California",
        "status": "Available"
      }, {
        "id": 36,
        "name": "Ezri",
        "lastName": "Januszewski",
        "phone": "9715976052",
        "email": "ejanuszewskiz@yellowbook.com",
        "anualRevenue": 80536,
        "registrationDate": "05/20/2023",
        "state": "Oregon",
        "status": "Not Available"
      }, {
        "id": 37,
        "name": "Rory",
        "lastName": "Christley",
        "phone": "3349850513",
        "email": "rchristley10@constantcontact.com",
        "anualRevenue": 74910,
        "registrationDate": "07/23/2023",
        "state": "Alabama",
        "status": "Not Available"
      }, {
        "id": 38,
        "name": "Kirbee",
        "lastName": "McCluskey",
        "phone": "4049766551",
        "email": "kmccluskey11@acquirethisname.com",
        "anualRevenue": 64596,
        "registrationDate": "10/13/2023",
        "state": "Georgia",
        "status": "Not Available"
      }, {
        "id": 39,
        "name": "Catlee",
        "lastName": "Danson",
        "phone": "2058941846",
        "email": "cdanson12@dmoz.org",
        "anualRevenue": 22261,
        "registrationDate": "04/22/2023",
        "state": "Alabama",
        "status": "Available"
      }, {
        "id": 40,
        "name": "Sherwynd",
        "lastName": "Tonkin",
        "phone": "5157348261",
        "email": "stonkin13@goo.ne.jp",
        "anualRevenue": 71844,
        "registrationDate": "02/10/2023",
        "state": "Iowa",
        "status": "Not Available"
      }, {
        "id": 41,
        "name": "Pamella",
        "lastName": "Whetnall",
        "phone": "2066454632",
        "email": "pwhetnall14@yellowbook.com",
        "anualRevenue": 13929,
        "registrationDate": "01/05/2024",
        "state": "Washington",
        "status": "Not Available"
      }, {
        "id": 42,
        "name": "Fabe",
        "lastName": "Murdy",
        "phone": "7637713447",
        "email": "fmurdy15@so-net.ne.jp",
        "anualRevenue": 14292,
        "registrationDate": "02/14/2023",
        "state": "Minnesota",
        "status": "Available"
      }, {
        "id": 43,
        "name": "Pippo",
        "lastName": "Ghiron",
        "phone": "7243337332",
        "email": "pghiron16@ow.ly",
        "anualRevenue": 99487,
        "registrationDate": "11/27/2023",
        "state": "Pennsylvania",
        "status": "Not Available"
      }, {
        "id": 44,
        "name": "Ardis",
        "lastName": "Edmonson",
        "phone": "7752202610",
        "email": "aedmonson17@google.fr",
        "anualRevenue": 67082,
        "registrationDate": "11/18/2023",
        "state": "Nevada",
        "status": "Not Available"
      }, {
        "id": 45,
        "name": "Eulalie",
        "lastName": "Grievson",
        "phone": "5172532902",
        "email": "egrievson18@amazon.de",
        "anualRevenue": 49818,
        "registrationDate": "10/15/2023",
        "state": "Michigan",
        "status": "Available"
      }, {
        "id": 46,
        "name": "Flossi",
        "lastName": "Tineman",
        "phone": "6232363972",
        "email": "ftineman19@tiny.cc",
        "anualRevenue": 35372,
        "registrationDate": "05/04/2023",
        "state": "Arizona",
        "status": "Available"
      }, {
        "id": 47,
        "name": "Temple",
        "lastName": "Eastam",
        "phone": "9017774210",
        "email": "teastam1a@shareasale.com",
        "anualRevenue": 30591,
        "registrationDate": "04/22/2023",
        "state": "Tennessee",
        "status": "Available"
      }, {
        "id": 48,
        "name": "Thelma",
        "lastName": "Gainforth",
        "phone": "5155867366",
        "email": "tgainforth1b@facebook.com",
        "anualRevenue": 22925,
        "registrationDate": "10/30/2023",
        "state": "Iowa",
        "status": "Available"
      }, {
        "id": 49,
        "name": "Nada",
        "lastName": "Flood",
        "phone": "7201745990",
        "email": "nflood1c@wp.com",
        "anualRevenue": 37234,
        "registrationDate": "11/18/2023",
        "state": "Colorado",
        "status": "Not Available"
      }, {
        "id": 50,
        "name": "Bianca",
        "lastName": "Rubenchik",
        "phone": "3349623207",
        "email": "brubenchik1d@twitter.com",
        "anualRevenue": 22775,
        "registrationDate": "03/18/2023",
        "state": "Alabama",
        "status": "Not Available"
    }
]